version: '3'

services:
    database:
      image: postgres:11-alpine
      restart: always
      container_name: ex1
      ports:
        - 7778:5432
      environment:
          POSTGRES_DB: ex1
          POSTGRES_USER: marcelo
          POSTGRES_PASSWORD: 123456